# Standards: 0.11
---

- include: "level-2/6.1.1.yml"
  when: "'6.1.1' not in cis_level_2_exclusions"
- include: "level-2/4.1.1.2.yml"
  when: "'4.1.1.2' not in cis_level_2_exclusions" 
- include: "level-2/4.1.1.3.yml"
  when: "'4.1.1.3' not in cis_level_2_exclusions"
- include: "level-2/4.1.2.yml"
  when: "'4.1.2' not in cis_level_2_exclusions"
- include: "level-2/4.1.4.yml"
  when: "'4.1.4' not in cis_level_2_exclusions" 
- include: "level-2/4.1.5.yml"
  when: "'4.1.5' not in cis_level_2_exclusions"
- include: "level-2/4.1.6.yml"
  when: "'4.1.6' not in cis_level_2_exclusions"
- include: "level-2/4.1.7.yml"
  when: "'4.1.7' not in cis_level_2_exclusions"
       
