# Standards: 0.11
---

# 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)

- name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
  selinux:
    policy: targeted
    state: enforcing
  tags:
      - level-1
      - section-1
      - "1.1.11"
      - scored
