# Standards: 0.11
---

# rsyslog is the default for amazon linux - skipping
# 4.2.2.2 Ensure logging is configured
# rsyslog is the default for amazon linux
- name: 4.2.2.2 - Ensure logging is configured
  debug:
    msg: "WARNING - This check has not been implemented yet."
  tags:
    - level-1
    - section-4
    - "4.2.2.2"
    - not-scored
    - todo


